### ISSUE TITLE
Pls 🙏 Fix

### ISSUE THREAD

**Issue by Asuna3244** [alvin0319/GroupsAPI#21] opened 2022-05-11 10:29 UTC
[12:28:36.107] [Server thread/CRITICAL]: TypeError: "alvin0319\GroupsAPI\GroupsAPI::getChatFormat(): Argument #1 ($group) must be of type string, null given, called in phar:///home/minecraft/plugins/GroupsAPI.phar/src/alvin0319/GroupsAPI/user/Member.php on line 248" (EXCEPTION) in "plugins/GroupsAPI.phar/src/alvin0319/GroupsAPI/GroupsAPI" at line 249

**Comment by alvin0319** [comment] 2022-06-04 07:25
Duplicate of #17

**Closed by alvin0319** 2022-06-04 07:25 UTC
